[book]
title = "Изучение Rust с помощью слишком большого количества списков"
author = "Aria Desires"
description = "Изучение Rust с помощью слишком большого количества списков"

[build]
build-dir = "book"
create-missing = false

[output.html]
git-repository-url = "https://github.com/rust-unofficial/too-many-lists"

[output.html.search]
limit-results = 30
